version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.6-stretch
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
  test:
    docker:
      - image: circleci/ruby:2.6.6-stretch

    working_directory: ~/repo

    steps:
      - run: echo test step

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build